name: 'Pull Request Actions'
description: 'This action will facilitate adding feature branch URLs to Pull Requests and Jira Tickets'
inputs:
  GHA_ACCESS_TOKEN:
    description: 'GitHub Actions Access Token'
    required: false

  GHA_ACCESS_USER:
    description: 'GitHub Actions Access Username'
    required: false

  branch_name:
    description: 'Branch Name'
    required: false

  JIRA_BASE_URL:
    description: 'Link to hosted Jira instance'
    required: false

  JIRA_USER_EMAIL:
    description: 'User email to use for managing Jira API'
    required: false

  JIRA_API_TOKEN:
    description: 'API Token to authorize Jira'
    required: false

  allow-repeats:
    description: 'Allow messages to be repeated.'
    required: false
    default: 'false'

  url:
    description: 'URL to use in feature branch PR comment'
    required: false
    default: ''

  endpoint:
    description: 'Endpoint to append to the feature branch URL'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Get Branch Name
      id: branch
      run: |
        import os
        env_file = os.getenv('GITHUB_OUTPUT')
        
        branch = ""
        if len("${{ inputs.branch_name }}") > 0:
          branch = "${{ inputs.branch_name }}".upper()
        elif "${{ github.event_name }}" == "pull_request":
          branch = "${{ github.head_ref }}".upper()
        elif "${{ github.event_name }}" == "push":
          branch = "${{ github.ref_name }}".upper()
        
        with open(env_file, "a") as output_file:
          output_file.write("branch_name=%s" % branch)
      shell: python
      env:
        GITHUB_OUTPUT: $GITHUB_OUTPUT

    - name: Extract Issue Tags
      id: issues
      uses: Renddslow/prepare-branch-commit@v1
      with:
        branch-name: ${{ steps.branch.outputs.branch_name }}

    - name: Prepare Jira Links
      id: jira-links
      run: |
        ISSUES="${{ steps.issues.outputs.issue-tags }}"
        ISSUE_STRING=""

        if [ -n "${{ inputs.JIRA_BASE_URL }}" ]; then
          for issue in ${ISSUES//,/ }
          do
            ISSUE_STRING+=" [[$issue](${{ inputs.JIRA_BASE_URL }}/browse/$issue)]"
          done
        else
          ISSUE_STRING="$ISSUES"
        fi

        echo "issue-string=$ISSUE_STRING" >> $GITHUB_OUTPUT
      shell: bash

    - name: Prepare PR Comment
      id: pr-comment
      run: |
        OUTPUT_STRING=""

        if [ -n "${{ steps.jira-links.outputs.issue-string }}" ]; then
          OUTPUT_STRING+="Jira Tickets: ${{ steps.jira-links.outputs.issue-string }}"
        fi

        if [ -n "${{ steps.jira-links.outputs.issue-string }}" ] && [ -n "${{ inputs.url }}" ]; then
          OUTPUT_STRING+="<br/><br/>"
        fi

        if [ -n "${{ inputs.url }}" ]; then
          OUTPUT_STRING+="Feature Branch: ${{ inputs.url }}${{ inputs.endpoint }}"
        fi

        echo "comment-string=$OUTPUT_STRING" >> $GITHUB_OUTPUT
      shell: bash

    - name: Add PR comment
      # Commit equivalent to https://github.com/mshick/add-pr-comment/releases/tag/v2
      if: steps.pr-comment.outputs.comment-string != ''
      uses: mshick/add-pr-comment@a65df5f64fc741e91c59b8359a4bc56e57aaf5b1
      with:
        repo-token: ${{ inputs.GHA_ACCESS_TOKEN }}
        allow-repeats: ${{ inputs.allow-repeats }}
        message: ${{ steps.pr-comment.outputs.comment-string }}

    - name: Continue with Jira Automation
      if: inputs.url != '' && inputs.JIRA_BASE_URL != '' && inputs.JIRA_USER_EMAIL != '' && inputs.JIRA_API_TOKEN != '' && steps.issues.outputs.issue-tags != ''
      id: jira
      run: echo "continue=true" >> $GITHUB_OUTPUT
      shell: bash

    - name: Jira Login
      if: steps.jira.outputs.continue == 'true'
      uses: atlassian/gajira-login@90a599561baaf8c05b080645ed73db7391c246ed
      env:
        JIRA_BASE_URL: ${{ inputs.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ inputs.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ inputs.JIRA_API_TOKEN }}

    - name: Comment on issue
      if: steps.jira.outputs.continue == 'true'
      uses: dmsi-io/gajira-comment@v2
      with:
        issue: ${{ steps.issues.outputs.issue-tags }}
        comment: 'Feature branch has been deployed at: ${{ inputs.url }}${{ inputs.endpoint }}'
        allow-repeats: ${{ inputs.allow-repeats }}
