name: 'Pull Request Actions'
description: 'This action will facilitate adding feature branch URLs to Pull Requests and Jira Tickets'
inputs:
  GHA_ACCESS_TOKEN:
    description: 'GitHub Actions Access Token'
    required: false

  GHA_ACCESS_USER: 
    description: 'GitHub Actions Access Username'
    required: false

  branch_name:
    description: 'Branch Name'
    required: false
    default: ${{ github.head_ref }}

  url: 
    description: 'URL to use in feature branch PR comment'
    required: true

  endpoint:
    description: 'Endpoint to append to the feature branch URL'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Extract Issue Tags
      id: issues
      uses: Renddslow/prepare-branch-commit@v1.0.1
      with:
        branch-name: ${{ inputs.branch_name }}

    - name: Add PR comment
      uses: mshick/add-pr-comment@v1
      with:
        repo-token: ${{ inputs.GHA_ACCESS_TOKEN }}
        repo-token-user-login: ${{ inputs.GHA_ACCESS_USER }}
        message: |
          Jira Tickets: ${{ steps.issues.outputs.issue-tags }}
          Feature Branch: ${{ inputs.url }}${{ inputs.endpoint }}