name: Test gha-pull-request

on: 
  - push

jobs:
  issue-tags:
    runs-on: ubuntu-latest
    name: Test gha-pull-request
    steps:
      - name: Test gha-pull-request
        uses: dmsi-io/gha-pull-request@main
        with:
          GHA_ACCESS_TOKEN: ${{ secrets.GHA_ACCESS_TOKEN }}
          url: 'https://example.com'
          endpoint: '/door-maintenance'
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}