name: Test gha-pull-request

on: 
  - push

jobs:
  issue-tags:
    runs-on: ubuntu-latest
    name: Test gha-pull-request
    steps:
      - name: Test gha-pull-request
        uses: dmsi-io/gha-pull-request@main
        with:
          url: 'https://example.com'
          endpoint: '/door-maintenance'