name: 'Run gha-pull-request'

on:
  push:
    branch:
      - test

jobs:
  test-pr:
    name: 'Run gha-pull-request'
    runs-on: ubuntu-latest
    steps:
      - name: Get Branch Name
        id: branch
        run: |
          import os
          env_file = os.getenv('GITHUB_OUTPUT')

          branch = ""
          if len("${{ inputs.branch_name }}") > 0:
            branch = "${{ inputs.branch_name }}".upper()
          elif "${{ github.event_name }}" == "pull_request":
            branch = "${{ github.head_ref }}".upper()
          elif "${{ github.event_name }}" == "push":
            branch = "${{ github.ref_name }}".upper()

          with open(env_file, "a") as output_file:
            print(env_file)
            print("branch=%s" % branch)
            output_file.write("branch=%s" % branch)
        shell: python
        env:
          GITHUB_OUTPUT: $GITHUB_OUTPUT

      - name: Print outputs
        run: echo "OUTPUTS=$OUTPUTS"
        env:
          OUTPUTS: ${{ toJSON(steps.branch.outputs) }}
